server:
  port: 8190
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: root
    password:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 23053377844-eulbn7b8ovsr31lgvo72135nsl0s950b.apps.googleusercontent.com
            client-secret: zII7NlMtv5ru9zeuIz9sewDz
            scope:
              - email
              - profile
              - openid
            github:
              clientId: 05adffca120cfc8ffba4
              clientSecret: 4546e1ae6d4f1128d07959fed6711b7437bd31c0
              scope:
                - user
            facebook:
              clientId: 238999834836830
              clientSecret: 9a3ae93036bc4ceef119aed2d6f03972
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  secret: memes
