server:
  port: 8190
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-63-33-14-215.eu-west-1.compute.amazonaws.com:5432/d8smhtqvac0hln
    username: dzepunjkmctdaa
    password: f86f521799ba5cbd28fa3f0596507e19229b7f5ae6cbb6ab396facd7265ff36b
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 23053377844-eulbn7b8ovsr31lgvo72135nsl0s950b.apps.googleusercontent.com
            client-secret: zII7NlMtv5ru9zeuIz9sewDz
            scope:
              - email
              - profile
              - openid
          github:
            clientId: 05adffca120cfc8ffba4
            clientSecret: 4546e1ae6d4f1128d07959fed6711b7437bd31c0
            scope:
              - user
          facebook:
            clientId: 238999834836830
            clientSecret: 9a3ae93036bc4ceef119aed2d6f03972
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: memes
