server:
  port: 8190
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_ACCESS}
    username: ${JDBC_UN}
    password: ${JDBC_PASS}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLI_ID}
            client-secret: ${GOOGLE_CLI_SECRET}
            scope:
              - email
              - profile
              - openid
          github:
            clientId: ${GITHUB_CLI_ID}
            clientSecret: ${GITHUB_CLI_SECRET}
          facebook:
            clientId: ${FB_CLI_ID}
            clientSecret: ${FB_CLI_ID}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: memes
